module.exports = {
    roots: ['<rootDir>/'],
    collectCoverageFrom: [
        'src/**/*.{js,ts,jsx,tsx}',
        './*.{js,ts,jsx,tsx}',
        '!.eslint*.js',
        '!babel.*.js',
        '!commitlint.*.js',
        '!jest.*.js',
        '!lint-staged.*.js',
        '!prettier.*.js',
        '!release.*.js',
        '!**/*.d.{ts,tsx}',
        '!**/node_modules/**',
    ],
    preset: 'ts-jest',
    testRegex: '.spec.[jt]s$',
    moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx', 'json', 'node'],
    testEnvironment: 'node',
    coverageProvider: 'v8',
    collectCoverage: false,
    coverageDirectory: '<rootDir>/coverage/',
    coverageReporters: ['lcov', 'text', 'cobertura'],
    testPathIgnorePatterns: [],
}
